apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: sample-vpc
  namespace: crossplane-system
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 10.8.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: crossplane-provider-config
