apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: sample-cluster-sg
  namespace: crossplane-system
spec:
  forProvider:
    region: us-west-1
    vpcIdRef:
      name: sample-vpc  
    groupName: my-cool-ekscluster-sg
    description: Cluster communication with worker nodes
    # ignoreIngress: true
    # ignoreEgress: true
    ingress:
      - fromPort: 80
        toPort: 80
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 10.0.0.0/8
  providerConfigRef:
    name: crossplane-provider-config