apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: sample-sgr
  namespace: crossplane-system
spec:
  forProvider:
    region: us-west-1
    protocol: "tcp"
    fromPort: 443
    toPort: 443
    type: "ingress"
    securityGroupIdRef:
      name: sample-cluster-sg
    cidrBlock: "123.12.0.0/16" 
    description: "sample-sgr description"
  providerConfigRef:
    name: crossplane-provider-config